# Default application configuration
LOG_LEVEL: "info"
POSTGRES_DSN: "postgres://smsuser:smspassword@postgres:5432/sms_gateway_db?sslmode=disable"
NATS_URL: "nats://nats:4222"

# User Service
USER_SERVICE_GRPC_PORT: 50051
JWT_ACCESS_SECRET: "your_very_secret_access_key_env_override_in_prod_12345"
JWT_REFRESH_SECRET: "your_very_secret_refresh_key_env_override_in_prod_67890"
JWT_ACCESS_EXPIRY_HOURS: 1
JWT_REFRESH_EXPIRY_HOURS: 720

# Public API Service
PUBLIC_API_SERVICE_PORT: 8080
USER_SERVICE_GRPC_CLIENT_TARGET: "user-service:50051"

# Billing Service
BILLING_SERVICE_GRPC_PORT: 50052
BILLING_SERVICE_GRPC_CLIENT_TARGET: "billing-service:50052" # Added (use Docker Compose service name)
