auth_enabled: false
server:
  http_listen_port: 3100
  grpc_listen_port: 9096 # Added for completeness, though not strictly used by Promtail push

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki # Path for Loki's operational files
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler: # Added for completeness, not strictly used in this phase
  alertmanager_url: http://localhost:9093 # Placeholder

# Limits for local development, can be adjusted
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h # 7 days
  ingestion_rate_mb: 15
  ingestion_burst_size_mb: 20
