apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false # Loki is already default
    jsonData:
      manageAlerts: true
    editable: true
