// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/proto/billingservice/billing.proto

package billingservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BillingServiceInternal_CheckAndDeductCredit_FullMethodName = "/billingservice.BillingServiceInternal/CheckAndDeductCredit"
)

// BillingServiceInternalClient is the client API for BillingServiceInternal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceInternalClient interface {
	CheckAndDeductCredit(ctx context.Context, in *CheckAndDeductCreditRequest, opts ...grpc.CallOption) (*CheckAndDeductCreditResponse, error)
}

type billingServiceInternalClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceInternalClient(cc grpc.ClientConnInterface) BillingServiceInternalClient {
	return &billingServiceInternalClient{cc}
}

func (c *billingServiceInternalClient) CheckAndDeductCredit(ctx context.Context, in *CheckAndDeductCreditRequest, opts ...grpc.CallOption) (*CheckAndDeductCreditResponse, error) {
	out := new(CheckAndDeductCreditResponse)
	err := c.cc.Invoke(ctx, BillingServiceInternal_CheckAndDeductCredit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceInternalServer is the server API for BillingServiceInternal service.
// All implementations must embed UnimplementedBillingServiceInternalServer
// for forward compatibility
type BillingServiceInternalServer interface {
	CheckAndDeductCredit(context.Context, *CheckAndDeductCreditRequest) (*CheckAndDeductCreditResponse, error)
	mustEmbedUnimplementedBillingServiceInternalServer()
}

// UnimplementedBillingServiceInternalServer must be embedded to have forward compatible implementations.
type UnimplementedBillingServiceInternalServer struct {
}

func (UnimplementedBillingServiceInternalServer) CheckAndDeductCredit(context.Context, *CheckAndDeductCreditRequest) (*CheckAndDeductCreditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAndDeductCredit not implemented")
}
func (UnimplementedBillingServiceInternalServer) mustEmbedUnimplementedBillingServiceInternalServer() {
}

// UnsafeBillingServiceInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceInternalServer will
// result in compilation errors.
type UnsafeBillingServiceInternalServer interface {
	mustEmbedUnimplementedBillingServiceInternalServer()
}

func RegisterBillingServiceInternalServer(s grpc.ServiceRegistrar, srv BillingServiceInternalServer) {
	s.RegisterService(&BillingServiceInternal_ServiceDesc, srv)
}

func _BillingServiceInternal_CheckAndDeductCredit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAndDeductCreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceInternalServer).CheckAndDeductCredit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingServiceInternal_CheckAndDeductCredit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceInternalServer).CheckAndDeductCredit(ctx, req.(*CheckAndDeductCreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingServiceInternal_ServiceDesc is the grpc.ServiceDesc for BillingServiceInternal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingServiceInternal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "billingservice.BillingServiceInternal",
	HandlerType: (*BillingServiceInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAndDeductCredit",
			Handler:    _BillingServiceInternal_CheckAndDeductCredit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/billingservice/billing.proto",
}
