// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: phonebookservice/phonebook.proto

package phonebookservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PhonebookService_CreatePhonebook_FullMethodName = "/phonebookservice.PhonebookService/CreatePhonebook"
	PhonebookService_GetPhonebook_FullMethodName    = "/phonebookservice.PhonebookService/GetPhonebook"
	PhonebookService_ListPhonebooks_FullMethodName  = "/phonebookservice.PhonebookService/ListPhonebooks"
	PhonebookService_UpdatePhonebook_FullMethodName = "/phonebookservice.PhonebookService/UpdatePhonebook"
	PhonebookService_DeletePhonebook_FullMethodName = "/phonebookservice.PhonebookService/DeletePhonebook"
	PhonebookService_CreateContact_FullMethodName   = "/phonebookservice.PhonebookService/CreateContact"
	PhonebookService_GetContact_FullMethodName      = "/phonebookservice.PhonebookService/GetContact"
	PhonebookService_ListContacts_FullMethodName    = "/phonebookservice.PhonebookService/ListContacts"
	PhonebookService_UpdateContact_FullMethodName   = "/phonebookservice.PhonebookService/UpdateContact"
	PhonebookService_DeleteContact_FullMethodName   = "/phonebookservice.PhonebookService/DeleteContact"
)

// PhonebookServiceClient is the client API for PhonebookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhonebookServiceClient interface {
	// Phonebook operations
	CreatePhonebook(ctx context.Context, in *CreatePhonebookRequest, opts ...grpc.CallOption) (*CreatePhonebookResponse, error)
	GetPhonebook(ctx context.Context, in *GetPhonebookRequest, opts ...grpc.CallOption) (*GetPhonebookResponse, error)
	ListPhonebooks(ctx context.Context, in *ListPhonebooksRequest, opts ...grpc.CallOption) (*ListPhonebooksResponse, error)
	UpdatePhonebook(ctx context.Context, in *UpdatePhonebookRequest, opts ...grpc.CallOption) (*UpdatePhonebookResponse, error)
	DeletePhonebook(ctx context.Context, in *DeletePhonebookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Contact operations
	CreateContact(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error)
	GetContact(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*GetContactResponse, error)
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error)
	DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type phonebookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPhonebookServiceClient(cc grpc.ClientConnInterface) PhonebookServiceClient {
	return &phonebookServiceClient{cc}
}

func (c *phonebookServiceClient) CreatePhonebook(ctx context.Context, in *CreatePhonebookRequest, opts ...grpc.CallOption) (*CreatePhonebookResponse, error) {
	out := new(CreatePhonebookResponse)
	err := c.cc.Invoke(ctx, PhonebookService_CreatePhonebook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) GetPhonebook(ctx context.Context, in *GetPhonebookRequest, opts ...grpc.CallOption) (*GetPhonebookResponse, error) {
	out := new(GetPhonebookResponse)
	err := c.cc.Invoke(ctx, PhonebookService_GetPhonebook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) ListPhonebooks(ctx context.Context, in *ListPhonebooksRequest, opts ...grpc.CallOption) (*ListPhonebooksResponse, error) {
	out := new(ListPhonebooksResponse)
	err := c.cc.Invoke(ctx, PhonebookService_ListPhonebooks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) UpdatePhonebook(ctx context.Context, in *UpdatePhonebookRequest, opts ...grpc.CallOption) (*UpdatePhonebookResponse, error) {
	out := new(UpdatePhonebookResponse)
	err := c.cc.Invoke(ctx, PhonebookService_UpdatePhonebook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) DeletePhonebook(ctx context.Context, in *DeletePhonebookRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PhonebookService_DeletePhonebook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) CreateContact(ctx context.Context, in *CreateContactRequest, opts ...grpc.CallOption) (*CreateContactResponse, error) {
	out := new(CreateContactResponse)
	err := c.cc.Invoke(ctx, PhonebookService_CreateContact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) GetContact(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*GetContactResponse, error) {
	out := new(GetContactResponse)
	err := c.cc.Invoke(ctx, PhonebookService_GetContact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, PhonebookService_ListContacts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error) {
	out := new(UpdateContactResponse)
	err := c.cc.Invoke(ctx, PhonebookService_UpdateContact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phonebookServiceClient) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PhonebookService_DeleteContact_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhonebookServiceServer is the server API for PhonebookService service.
// All implementations must embed UnimplementedPhonebookServiceServer
// for forward compatibility
type PhonebookServiceServer interface {
	// Phonebook operations
	CreatePhonebook(context.Context, *CreatePhonebookRequest) (*CreatePhonebookResponse, error)
	GetPhonebook(context.Context, *GetPhonebookRequest) (*GetPhonebookResponse, error)
	ListPhonebooks(context.Context, *ListPhonebooksRequest) (*ListPhonebooksResponse, error)
	UpdatePhonebook(context.Context, *UpdatePhonebookRequest) (*UpdatePhonebookResponse, error)
	DeletePhonebook(context.Context, *DeletePhonebookRequest) (*emptypb.Empty, error)
	// Contact operations
	CreateContact(context.Context, *CreateContactRequest) (*CreateContactResponse, error)
	GetContact(context.Context, *GetContactRequest) (*GetContactResponse, error)
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	UpdateContact(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error)
	DeleteContact(context.Context, *DeleteContactRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedPhonebookServiceServer()
}

// UnimplementedPhonebookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPhonebookServiceServer struct {
}

func (UnimplementedPhonebookServiceServer) CreatePhonebook(context.Context, *CreatePhonebookRequest) (*CreatePhonebookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePhonebook not implemented")
}
func (UnimplementedPhonebookServiceServer) GetPhonebook(context.Context, *GetPhonebookRequest) (*GetPhonebookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPhonebook not implemented")
}
func (UnimplementedPhonebookServiceServer) ListPhonebooks(context.Context, *ListPhonebooksRequest) (*ListPhonebooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPhonebooks not implemented")
}
func (UnimplementedPhonebookServiceServer) UpdatePhonebook(context.Context, *UpdatePhonebookRequest) (*UpdatePhonebookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePhonebook not implemented")
}
func (UnimplementedPhonebookServiceServer) DeletePhonebook(context.Context, *DeletePhonebookRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePhonebook not implemented")
}
func (UnimplementedPhonebookServiceServer) CreateContact(context.Context, *CreateContactRequest) (*CreateContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContact not implemented")
}
func (UnimplementedPhonebookServiceServer) GetContact(context.Context, *GetContactRequest) (*GetContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContact not implemented")
}
func (UnimplementedPhonebookServiceServer) ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContacts not implemented")
}
func (UnimplementedPhonebookServiceServer) UpdateContact(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContact not implemented")
}
func (UnimplementedPhonebookServiceServer) DeleteContact(context.Context, *DeleteContactRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}
func (UnimplementedPhonebookServiceServer) mustEmbedUnimplementedPhonebookServiceServer() {}

// UnsafePhonebookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhonebookServiceServer will
// result in compilation errors.
type UnsafePhonebookServiceServer interface {
	mustEmbedUnimplementedPhonebookServiceServer()
}

func RegisterPhonebookServiceServer(s grpc.ServiceRegistrar, srv PhonebookServiceServer) {
	s.RegisterService(&PhonebookService_ServiceDesc, srv)
}

func _PhonebookService_CreatePhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePhonebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).CreatePhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_CreatePhonebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).CreatePhonebook(ctx, req.(*CreatePhonebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_GetPhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPhonebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).GetPhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_GetPhonebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).GetPhonebook(ctx, req.(*GetPhonebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_ListPhonebooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPhonebooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).ListPhonebooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_ListPhonebooks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).ListPhonebooks(ctx, req.(*ListPhonebooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_UpdatePhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePhonebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).UpdatePhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_UpdatePhonebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).UpdatePhonebook(ctx, req.(*UpdatePhonebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_DeletePhonebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePhonebookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).DeletePhonebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_DeletePhonebook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).DeletePhonebook(ctx, req.(*DeletePhonebookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_CreateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).CreateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_CreateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).CreateContact(ctx, req.(*CreateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_GetContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).GetContact(ctx, req.(*GetContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_ListContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_UpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).UpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_UpdateContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).UpdateContact(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhonebookService_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhonebookServiceServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhonebookService_DeleteContact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhonebookServiceServer).DeleteContact(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhonebookService_ServiceDesc is the grpc.ServiceDesc for PhonebookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhonebookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phonebookservice.PhonebookService",
	HandlerType: (*PhonebookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePhonebook",
			Handler:    _PhonebookService_CreatePhonebook_Handler,
		},
		{
			MethodName: "GetPhonebook",
			Handler:    _PhonebookService_GetPhonebook_Handler,
		},
		{
			MethodName: "ListPhonebooks",
			Handler:    _PhonebookService_ListPhonebooks_Handler,
		},
		{
			MethodName: "UpdatePhonebook",
			Handler:    _PhonebookService_UpdatePhonebook_Handler,
		},
		{
			MethodName: "DeletePhonebook",
			Handler:    _PhonebookService_DeletePhonebook_Handler,
		},
		{
			MethodName: "CreateContact",
			Handler:    _PhonebookService_CreateContact_Handler,
		},
		{
			MethodName: "GetContact",
			Handler:    _PhonebookService_GetContact_Handler,
		},
		{
			MethodName: "ListContacts",
			Handler:    _PhonebookService_ListContacts_Handler,
		},
		{
			MethodName: "UpdateContact",
			Handler:    _PhonebookService_UpdateContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _PhonebookService_DeleteContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phonebookservice/phonebook.proto",
}
